import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion,MotionConfig} from 'motion/react';
import {ArrowUpRight,ArrowRight,Command,Layers3,Activity,PanelRightOpen,Plus,X,RotateCcw,CornerDownLeft,ChevronDown} from 'lucide-react';
import {api,dateLabel,money} from './api';
import type {Analysis,Company,Job,Claim,Source} from './types';
import {PriceChart} from './components/PriceChart';
import {Evidence} from './components/Evidence';

const names:Record<string,string>={AAPL:'Apple Inc.',MSFT:'Microsoft',NVDA:'NVIDIA'};
const suggestions=[{label:'Financial performance',query:'What does {company} latest quarterly filing say about its recent financial performance?'},{label:'Business risks',query:'What are {company} main current business risks?'},{label:'Cash & liquidity',query:'How much cash and cash equivalents does {company} report in its latest quarterly filing?'}];
function saved():Analysis|null{try{return JSON.parse(sessionStorage.getItem('quant-research')||'null')}catch{return null}}
function Mark({small=false}:{small?:boolean}){return <svg className={small?'mark small':'mark'} viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M10 9h19v20H10zM23 24l10 10M6 16h9M24 5v9" stroke="currentColor" strokeWidth="2.2"/></svg>}
function Emphasis({text}:{text:string}){return <>{text.split(/(\$[\d,.]+(?:\s+(?:million|billion))?|\b\d+(?:\.\d+)?\s*%)/g).map((s,i)=>i%2?<strong key={i} className="financial-number">{s}</strong>:s)}</>}
function Citation({id,sources,onClick}:{id:string;sources:Source[];onClick:(id:string)=>void}){const s=sources.find(x=>x.source_id===id);return <button className="citation" onClick={()=>onClick(id)} aria-label={`Inspect evidence ${id}`}><span className="citation-cross">+</span>{s?.filing_type?`${s.filing_type} · ${dateLabel(s.filing_date)}`:id.endsWith('MARKET')?'Market data':'News evidence'}<ArrowUpRight size={11}/></button>}
function ClaimLine({claim,i,sources,onSource}:{claim:Claim;i:number;sources:Source[];onSource:(id:string)=>void}){return <motion.div className={`claim-line ${i===0?'lead-claim':''}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.2,delay:i*.045}}><span className="claim-index">{String(i+1).padStart(2,'0')}</span><div><span className="claim-kind">{claim.kind==='financial'?'REPORTED FIGURE':claim.kind.toUpperCase()}</span><p><Emphasis text={claim.text}/></p><div className="citations">{claim.sources.map(id=><Citation key={id} id={id} sources={sources} onClick={onSource}/>)}</div></div></motion.div>}

export default function App(){
 const [analysis,setAnalysis]=useState<Analysis|null>(saved);const [ticker,setTicker]=useState(()=>saved()?.companies[0]?.ticker||'AAPL');
 const [company,setCompany]=useState<Company|null>(()=>saved()?.companies[0]||null);const [contextBusy,setContextBusy]=useState(true);const [contextError,setContextError]=useState('');
 const [compare,setCompare]=useState('');const [question,setQuestion]=useState('');const [job,setJob]=useState<Job|null>(null);const [error,setError]=useState('');
 const [selected,setSelected]=useState<string|null>(null);const [evidenceTab,setEvidenceTab]=useState<'filings'|'news'>('filings');const [evidenceOpen,setEvidenceOpen]=useState(false);const [activeNav,setActiveNav]=useState('research');
 const input=useRef<HTMLTextAreaElement>(null);const research=useRef<HTMLElement>(null);const plot=useRef<HTMLDivElement>(null);
 const busy=!!job&&['queued','retrieving','verifying'].includes(job.stage);
 useEffect(()=>{let live=true;setContextBusy(true);setContextError('');api<Company>(`/company/${ticker}`).then(c=>{if(live)setCompany(c)}).catch(e=>{if(live)setContextError(e.message)}).finally(()=>{if(live)setContextBusy(false)});return()=>{live=false}},[ticker]);
 useEffect(()=>{if(!job?.id||job.stage==='complete'||job.stage==='error')return;let live=true;const poll=window.setInterval(()=>{api<Job>(`/analyses/${job.id}`).then(j=>{if(!live)return;setJob(j);if(j.stage==='complete'&&j.result){setAnalysis(j.result);setCompany(j.result.companies[0]);try{sessionStorage.setItem('quant-research',JSON.stringify(j.result))}catch{}setSelected(null);setActiveNav('research');requestAnimationFrame(()=>research.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))}if(j.stage==='error')setError(j.message||'Analysis could not be completed.')}).catch(e=>{if(live){setError(e.message);setJob(null)}})},1100);return()=>{live=false;clearInterval(poll)}},[job?.id,job?.stage]);
 useEffect(()=>{function keys(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();input.current?.focus()}if(e.key==='Escape')setEvidenceOpen(false)}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys)},[]);
 async function submit(q=question){if(busy||q.trim().length<5)return;setQuestion(q);setError('');setJob({id:'',stage:'queued'});research.current?.scrollIntoView({behavior:'smooth',block:'start'});try{setJob(await api<Job>('/analyses',{method:'POST',body:JSON.stringify({question:q,tickers:compare?[ticker,compare]:[ticker]})}))}catch(e){setError((e as Error).message);setJob(null)}}
 function changeTicker(t:string){setTicker(t);setCompany(null);setAnalysis(null);setSelected(null);setCompare('');setQuestion('');setJob(null);sessionStorage.removeItem('quant-research')}
 function showSource(id:string){setSelected(id);setEvidenceOpen(true);setEvidenceTab(id.endsWith(':NEWS')?'news':'filings')}
 function nav(to:string){setActiveNav(to);if(to==='research')research.current?.scrollIntoView({behavior:'smooth',block:'start'});if(to==='market')plot.current?.scrollIntoView({behavior:'smooth',block:'start'});if(to==='evidence')setEvidenceOpen(true)}
 const quote=company?.quote;const latest=company?.filings.find(f=>f.filing_type==='10-Q');
 const stage=job?.stage;const title=stage==='verifying'?'Checking each claim against its source.':stage==='retrieving'?'Reading the evidence.':'Preparing your research.';
 return <MotionConfig reducedMotion="user"><div className="app-shell">
  <nav className="navigation" aria-label="Workspace navigation"><a className="brand-mark" href="#" aria-label="Quant GPT home" onClick={e=>{e.preventDefault();nav('research')}}><Mark/></a><div className="nav-links"><button className={activeNav==='research'?'active':''} onClick={()=>nav('research')} aria-label="Research workspace" title="Research"><Layers3 size={19}/></button><button className={activeNav==='market'?'active':''} onClick={()=>nav('market')} aria-label="Market chart" title="Market"><Activity size={19}/></button><button className={activeNav==='evidence'?'active':''} onClick={()=>nav('evidence')} aria-label="Open evidence desk" title="Evidence"><PanelRightOpen size={19}/></button></div><div className="rail-base"><span className="status-pip" title="Local research workspace"/><span className="vertical-label">INTELLIGENCE / 02</span></div></nav>
  <header className="masthead"><div className="wordmark">QUANT<span>GPT</span><i>/</i><small>FINANCIAL INTELLIGENCE</small></div><div className="masthead-right"><span className="header-quote">{ticker} <b>{quote?.available?money(quote.price):'—'}</b><small>DAILY CLOSE</small></span><span className="system-label"><span className={`tiny-dot ${contextError?'warning':''}`}/>{contextBusy?'CONNECTING':contextError?'PARTIAL AVAILABILITY':'RESEARCH WORKSPACE'}</span><button className="keyboard-shortcut" onClick={()=>input.current?.focus()} title="Focus research command"><Command size={12}/> K</button></div></header>
  <div className="workspace">
   <main className="main-canvas">
    <section className="company-context" aria-label="Company context"><div className="context-kicker"><div className="ticker-control"><select aria-label="Research company" value={ticker} disabled={busy} onChange={e=>changeTicker(e.target.value)}>{Object.keys(names).map(t=><option key={t}>{t}</option>)}</select><ChevronDown size={12}/></div><span className="exchange">US EQUITY</span><div className="compare-control">{compare?<><span>×</span><select aria-label="Comparison company" value={compare} disabled={busy} onChange={e=>setCompare(e.target.value)}>{Object.keys(names).filter(t=>t!==ticker).map(t=><option key={t}>{t}</option>)}</select><button aria-label="Remove comparison" disabled={busy} onClick={()=>setCompare('')}><X size={12}/></button></>:<button disabled={busy} onClick={()=>setCompare(ticker==='MSFT'?'AAPL':'MSFT')}><Plus size={12}/> Compare</button>}</div></div>
    <div className="company-line"><div><h1>{company?.name||names[ticker]}{compare&&<span className="compare-name"> / {names[compare]}</span>}</h1><div className="company-subtitle"><span className="tiny-dot"/>{latest?<>LATEST IN INDEX <b>{latest.filing_type}</b> {dateLabel(latest.filing_date)}</>:contextBusy?'ESTABLISHING DATA CONTEXT':company?.filing_status==='empty'?'NO FILINGS IN CURRENT INDEX':'FILING STATUS UNAVAILABLE'}</div></div><div className="price-block"><span className="price">{quote?.available?money(quote.price):'—'}</span><div><span className={(quote?.change_percent_float||0)<0?'negative':'positive'}>{quote?.available?quote.change_percent_str:'Unavailable'}</span><span className="price-date">CLOSE · {quote?.date?dateLabel(quote.date):'DATE PENDING'}</span></div></div></div>
    </section>
    {contextError&&<div className="inline-notice">{contextError} Analysis can still be requested below.</div>}
    <div ref={plot} className="market-anchor"><PriceChart company={company} compact={!!analysis||busy}/></div>
    <section className="research-canvas" ref={research} aria-label="Research analysis">
     <div className="section-top"><span className="eyebrow"><span className="cross">+</span> INTELLIGENCE BRIEF</span><div>{analysis&&!busy&&<span className="verification-label">{analysis.claims.length} SOURCE-LINKED CLAIMS</span>}<button className="icon-button" aria-label="Clear analysis" title="New research" disabled={busy||!analysis} onClick={()=>{setAnalysis(null);setSelected(null);setQuestion('');sessionStorage.removeItem('quant-research')}}><RotateCcw size={13}/></button></div></div>
     <AnimatePresence mode="wait">{busy?<motion.div key="loading" className="analysis-loading" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="status"><div className="signal-loader"><span/><span/><span/><span/></div><span className="eyebrow">{stage==='verifying'?'EVIDENCE CHECK':'RESEARCH IN PROGRESS'}</span><h2>{title}</h2><p>{question}</p><div className="stage-track"><span className="done">01 / Context</span><span className={stage==='retrieving'||stage==='verifying'?'done':''}>02 / Retrieve</span><span className={stage==='verifying'?'done':''}>03 / Verify</span></div><small>Two-stage generation and evidence review. This can take a minute.</small></motion.div>:analysis?<motion.div key={analysis.completed_at} initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} className="analysis-result"><div className="brief-heading"><h2>{analysis.companies.length>1?'Comparative research':/risks?/i.test(analysis.question)?'The risk landscape':/cash|liquidity/i.test(analysis.question)?'Liquidity, examined':/quarter|financial performance/i.test(analysis.question)?'Quarterly performance':'Research findings'}<span className="title-period">.</span></h2><details className="brief-question"><summary>Research question</summary><p>{analysis.question}</p></details><div className="brief-meta">{analysis.companies.map(c=>c.ticker).join(' / ')}<span>·</span> SOURCE-GROUNDED RESEARCH <button className="mobile-evidence-link" onClick={()=>setEvidenceOpen(true)}>View evidence <ArrowUpRight size={12}/></button></div></div>{analysis.insufficient?<div className="insufficient"><span className="cross">+</span><h3>The evidence stops here.</h3><p>The supplied sources aren’t enough for a reliable answer. Try a narrower question or inspect the available filings.</p></div>:<>{analysis.claims.map((claim,i)=><ClaimLine key={i} claim={claim} i={i} sources={analysis.sources} onSource={showSource}/>)}</>}{analysis.notes.map((note,i)=><div className="analysis-note" key={i}>{note}</div>)}<div className="analysis-foot">Grounded in retrieved evidence. Not investment advice.</div></motion.div>:<motion.div key="empty" initial={{opacity:0}} animate={{opacity:1}} className="research-empty"><span className="folio-number">01 — RESEARCH</span><h2>Read the signal. <span>Trace the evidence.</span></h2><p>Interrogate company filings, market observations and news.<br className="desktop-break"/> Get an answer with a research trail you can inspect.</p><div className="starting-points">{suggestions.slice(0,2).map((s,i)=><button key={s.label} onClick={()=>submit(s.query.replace('{company}',`${names[ticker]}'s`))}><span>0{i+1}</span><b>{s.label}</b><ArrowUpRight size={16}/></button>)}</div></motion.div>}</AnimatePresence>
    </section>
   </main>
   <Evidence analysis={analysis} company={company} selected={selected} onSelect={setSelected} tab={evidenceTab} onTab={setEvidenceTab} open={evidenceOpen} onClose={()=>setEvidenceOpen(false)}/>
  </div>
  {evidenceOpen&&<button className="mobile-scrim" aria-label="Close evidence overlay" onClick={()=>setEvidenceOpen(false)}/>}
  <div className="command-dock"><div className="command-presets">{suggestions.map(s=><button key={s.label} disabled={busy} onClick={()=>{setQuestion(s.query.replace('{company}',`${names[ticker]}'s`));input.current?.focus()}}>{s.label}<ArrowUpRight size={10}/></button>)}</div><form onSubmit={e=>{e.preventDefault();submit()}}><div className={`command-input ${busy?'is-busy':''}`}><span className="command-glyph" aria-hidden="true">⌁</span><textarea ref={input} aria-label="Research question" placeholder={`Ask a financial question about ${names[ticker]}…`} value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1200} rows={1} disabled={busy} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}}/><button className="submit-command" type="submit" disabled={busy||question.trim().length<5} aria-label="Run analysis">{busy?<span className="button-loading"/>:<><span>Analyze</span><ArrowRight size={17}/></>}</button></div></form>{error?<div className="command-error" role="alert">{error}</div>:<div className="command-foot"><span>{ticker}{compare?` + ${compare}`:''}<span className="command-separator">/</span> SEC FILINGS + MARKET DATA + NEWS</span><span><CornerDownLeft size={10}/> RUN <span className="command-separator">·</span> SHIFT ↵ NEW LINE</span></div>}</div>
 </div></MotionConfig>
}
