export interface Quote {available:boolean;status:string;message:string;date:string|null;price?:number;volume?:number;change_percent_str?:string;change_percent_float?:number;fetched_at?:string}
export interface Article {title:string;description:string;source:string;url:string;published_at?:string;sentiment_label:string}
export interface News {available:boolean;status:string;message:string;overall_sentiment_label:string;articles:Article[];fetched_at?:string}
export interface Filing {filing_type:string;filing_date:string;accession_number:string}
export interface Company {ticker:string;name:string;quote:Quote|null;chart:{time:string;value:number}[];news:News;filings:Filing[];filing_status:string}
export interface Source {source_id:string;ticker:string;filing_type?:string;filing_date?:string;report_period_end?:string;accession?:string;source?:string;document?:string;chunk_id?:string;text:string;url?:string;kind?:string}
export interface Claim {text:string;sources:string[];kind:string}
export interface Analysis {question:string;claims:Claim[];notes:string[];insufficient:boolean;companies:Company[];sources:Source[];completed_at:number}
export interface Job {id:string;stage:'queued'|'retrieving'|'verifying'|'complete'|'error';result?:Analysis;message?:string}
